/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDataSourcesRouteImport } from './routes/_authenticated/data-sources'
import { Route as AuthenticatedFieldReportsRouteImport } from './routes/_authenticated/field-reports'
import { Route as AuthenticatedPredictionRouteImport } from './routes/_authenticated/prediction'
import { Route as AuthenticatedRiskMapRouteImport } from './routes/_authenticated/risk-map'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWhatIfRouteImport } from './routes/_authenticated/what-if'
import { Route as AuthenticatedRiskIdRouteImport } from './routes/_authenticated/risk.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataSourcesRoute =
  AuthenticatedDataSourcesRouteImport.update({
    id: '/data-sources',
    path: '/data-sources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFieldReportsRoute =
  AuthenticatedFieldReportsRouteImport.update({
    id: '/field-reports',
    path: '/field-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPredictionRoute = AuthenticatedPredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskMapRoute = AuthenticatedRiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatIfRoute = AuthenticatedWhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskIdRoute = AuthenticatedRiskIdRouteImport.update({
  id: '/risk/$id',
  path: '/risk/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-sources': typeof AuthenticatedDataSourcesRoute
  '/field-reports': typeof AuthenticatedFieldReportsRoute
  '/prediction': typeof AuthenticatedPredictionRoute
  '/risk-map': typeof AuthenticatedRiskMapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/what-if': typeof AuthenticatedWhatIfRoute
  '/risk/$id': typeof AuthenticatedRiskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-sources': typeof AuthenticatedDataSourcesRoute
  '/field-reports': typeof AuthenticatedFieldReportsRoute
  '/prediction': typeof AuthenticatedPredictionRoute
  '/risk-map': typeof AuthenticatedRiskMapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/what-if': typeof AuthenticatedWhatIfRoute
  '/risk/$id': typeof AuthenticatedRiskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-sources': typeof AuthenticatedDataSourcesRoute
  '/_authenticated/field-reports': typeof AuthenticatedFieldReportsRoute
  '/_authenticated/prediction': typeof AuthenticatedPredictionRoute
  '/_authenticated/risk-map': typeof AuthenticatedRiskMapRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/what-if': typeof AuthenticatedWhatIfRoute
  '/_authenticated/risk/$id': typeof AuthenticatedRiskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/analytics'
    | '/dashboard'
    | '/data-sources'
    | '/field-reports'
    | '/prediction'
    | '/risk-map'
    | '/settings'
    | '/what-if'
    | '/risk/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/analytics'
    | '/dashboard'
    | '/data-sources'
    | '/field-reports'
    | '/prediction'
    | '/risk-map'
    | '/settings'
    | '/what-if'
    | '/risk/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/alerts'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-sources'
    | '/_authenticated/field-reports'
    | '/_authenticated/prediction'
    | '/_authenticated/risk-map'
    | '/_authenticated/settings'
    | '/_authenticated/what-if'
    | '/_authenticated/risk/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-sources': {
      id: '/_authenticated/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof AuthenticatedDataSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field-reports': {
      id: '/_authenticated/field-reports'
      path: '/field-reports'
      fullPath: '/field-reports'
      preLoaderRoute: typeof AuthenticatedFieldReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prediction': {
      id: '/_authenticated/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof AuthenticatedPredictionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk-map': {
      id: '/_authenticated/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof AuthenticatedRiskMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/what-if': {
      id: '/_authenticated/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof AuthenticatedWhatIfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk/$id': {
      id: '/_authenticated/risk/$id'
      path: '/risk/$id'
      fullPath: '/risk/$id'
      preLoaderRoute: typeof AuthenticatedRiskIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataSourcesRoute: typeof AuthenticatedDataSourcesRoute
  AuthenticatedFieldReportsRoute: typeof AuthenticatedFieldReportsRoute
  AuthenticatedPredictionRoute: typeof AuthenticatedPredictionRoute
  AuthenticatedRiskMapRoute: typeof AuthenticatedRiskMapRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWhatIfRoute: typeof AuthenticatedWhatIfRoute
  AuthenticatedRiskIdRoute: typeof AuthenticatedRiskIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataSourcesRoute: AuthenticatedDataSourcesRoute,
  AuthenticatedFieldReportsRoute: AuthenticatedFieldReportsRoute,
  AuthenticatedPredictionRoute: AuthenticatedPredictionRoute,
  AuthenticatedRiskMapRoute: AuthenticatedRiskMapRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWhatIfRoute: AuthenticatedWhatIfRoute,
  AuthenticatedRiskIdRoute: AuthenticatedRiskIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
